# Generated by Django 6.0 on 2025-12-22 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_add_timestamps_to_source_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hub",
            fields=[
                (
                    "hub_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of the hub",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hub_physical_name",
                    models.CharField(
                        help_text="Physical name of the hub (e.g. hub_customer)",
                        max_length=255,
                    ),
                ),
                (
                    "hub_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Hub"),
                            ("reference", "Reference Hub"),
                        ],
                        default="standard",
                        help_text="Type of hub: standard or reference",
                        max_length=20,
                    ),
                ),
                (
                    "hub_hashkey_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the hub hashkey column (used only if hub_type = standard)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "create_record_tracking_satellite",
                    models.BooleanField(
                        default=False,
                        help_text="If true, a record-tracking satellite should be generated for this hub",
                    ),
                ),
                (
                    "create_effectivity_satellite",
                    models.BooleanField(
                        default=False,
                        help_text="If true, an effectivity satellite should be generated for this hub",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the hub was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the hub was last updated",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this hub belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hubs",
                        to="engine.project",
                    ),
                ),
            ],
            options={
                "db_table": "hub",
                "ordering": ["hub_physical_name"],
                "unique_together": {("project", "hub_physical_name")},
            },
        ),
        migrations.CreateModel(
            name="HubColumn",
            fields=[
                (
                    "hub_column_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of the hub column",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "column_name",
                    models.CharField(
                        help_text="Logical/target column name in the hub",
                        max_length=255,
                    ),
                ),
                (
                    "column_type",
                    models.CharField(
                        choices=[
                            ("business_key", "Business Key"),
                            ("additional_column", "Additional Column"),
                            ("reference_key", "Reference Key"),
                        ],
                        default="business_key",
                        help_text="Type of column: business_key, additional_column, or reference_key",
                        max_length=30,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        help_text="Sorting index to define ordering of hub columns"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the hub column was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the hub column was last updated",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        help_text="Hub this column belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="engine.hub",
                    ),
                ),
            ],
            options={
                "db_table": "hub_column",
                "ordering": ["sort_order"],
                "unique_together": {("hub", "column_name")},
            },
        ),
        migrations.CreateModel(
            name="HubSourceMapping",
            fields=[
                (
                    "hub_source_mapping_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of the hub-to-source mapping row",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary_source",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this mapping is the primary source for the hub",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the mapping was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the mapping was last updated",
                    ),
                ),
                (
                    "hub_column",
                    models.ForeignKey(
                        help_text="Hub column being mapped",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_mappings",
                        to="engine.hubcolumn",
                    ),
                ),
                (
                    "source_column",
                    models.ForeignKey(
                        help_text="Source column providing the data",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hub_mappings",
                        to="engine.sourcecolumn",
                    ),
                ),
            ],
            options={
                "db_table": "hub_source_mapping",
                "unique_together": {("hub_column", "source_column")},
            },
        ),
    ]
