# Generated by Django 6.0 on 2025-12-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_hub_hubcolumn_hubsourcemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='create_effectivity_satellite',
            field=models.BooleanField(default=True, help_text='If true, an effectivity satellite should be generated for this hub'),
        ),
    ]
