# Generated by Django 6.0 on 2025-12-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0004_change_effectivity_satellite_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubcolumn",
            name="sort_order",
            field=models.IntegerField(
                blank=True,
                help_text="Sorting index to define ordering of hub columns (auto-incremented if not provided)",
                null=True,
            ),
        ),
    ]
