# Generated by Django 6.0 on 2025-12-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0006_add_hub_to_hubsourcemapping"),
    ]

    operations = []
