# Generated by Django 6.0.4 on 2026-04-13 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_satellitecolumn_column_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencetable',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional group for organizing reference tables into subfolders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_tables', to='engine.group'),
        ),
        migrations.AlterField(
            model_name='linkcolumn',
            name='column_type',
            field=models.CharField(choices=[('payload', 'Payload'), ('additional_column', 'Additional Column'), ('dependent_child_key', 'dependent Child Key')], help_text='Type of column: payload or additional_column', max_length=20),
        ),
        migrations.AlterField(
            model_name='satellitecolumn',
            name='column_sort_order',
            field=models.PositiveIntegerField(blank=True, help_text='Display/generation order of this column within the satellite (1-based, unique per satellite, auto-assigned on creation).', null=True),
        ),
    ]
