# Generated by Django 6.0 on 2025-12-22 10:08

import datetime
import django.db.models.deletion
import engine.models.snapshot_control
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0008_make_hub_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hubsourcemapping",
            name="hub",
        ),
        migrations.CreateModel(
            name="SnapshotControlTable",
            fields=[
                (
                    "snapshot_control_table_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of the snapshot control table",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot_start_date",
                    models.DateField(
                        default=engine.models.snapshot_control.default_snapshot_start_date,
                        help_text="Start date for snapshot range (default: beginning of current year - 5)",
                    ),
                ),
                (
                    "snapshot_end_date",
                    models.DateField(
                        default=engine.models.snapshot_control.default_snapshot_end_date,
                        help_text="End date for snapshot range (default: end of current year + 5)",
                    ),
                ),
                (
                    "daily_snapshot_time",
                    models.TimeField(
                        default=datetime.time(8, 0),
                        help_text="Daily snapshot time (default: 08:00:00)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the snapshot control table was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the snapshot control table was last updated",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this snapshot control belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_control_tables",
                        to="engine.project",
                    ),
                ),
            ],
            options={
                "db_table": "snapshot_control_table",
                "ordering": ["project", "snapshot_start_date"],
            },
        ),
        migrations.CreateModel(
            name="SnapshotControlLogic",
            fields=[
                (
                    "snapshot_control_logic_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of the snapshot logic entry",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot_control_logic_column_name",
                    models.CharField(
                        help_text="Column name for this snapshot logic in generated structures",
                        max_length=255,
                    ),
                ),
                (
                    "snapshot_component",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("beginning_of_week", "Beginning of Week"),
                            ("end_of_week", "End of Week"),
                            ("beginning_of_month", "Beginning of Month"),
                            ("end_of_month", "End of Month"),
                            ("beginning_of_quarter", "Beginning of Quarter"),
                            ("end_of_quarter", "End of Quarter"),
                            ("beginning_of_year", "Beginning of Year"),
                            ("end_of_year", "End of Year"),
                        ],
                        help_text="When to take snapshots (daily, beginning/end of week/month/quarter/year)",
                        max_length=30,
                    ),
                ),
                (
                    "snapshot_duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration value for snapshot retention (e.g., 3, 6, 12)",
                        null=True,
                    ),
                ),
                (
                    "snapshot_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAY", "Day"),
                            ("WEEK", "Week"),
                            ("MONTH", "Month"),
                            ("QUARTER", "Quarter"),
                            ("YEAR", "Year"),
                        ],
                        help_text="Unit for duration: DAY, WEEK, MONTH, QUARTER, YEAR",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "snapshot_forever",
                    models.BooleanField(
                        default=False,
                        help_text="If true, snapshots are kept indefinitely (duration and unit must be NULL)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the snapshot logic was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the snapshot logic was last updated",
                    ),
                ),
                (
                    "snapshot_control_table",
                    models.ForeignKey(
                        help_text="Snapshot control table this logic belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logic_rules",
                        to="engine.snapshotcontroltable",
                    ),
                ),
            ],
            options={
                "db_table": "snapshot_control_logic",
                "ordering": ["snapshot_control_table", "snapshot_component"],
            },
        ),
    ]
