# Generated by Django 6.0.4 on 2026-04-15 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_referencetable_group_alter_linkcolumn_column_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional group for organizing pits into subfolders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pits', to='engine.group'),
        ),
    ]
