# Generated by Django 6.0 on 2025-12-22 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_remove_hubsourcemapping_hub_snapshotcontroltable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('satellite_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the satellite', primary_key=True, serialize=False)),
                ('satellite_physical_name', models.CharField(help_text='Physical name of the satellite (e.g. sat_customer_details)', max_length=255)),
                ('satellite_type', models.CharField(choices=[('standard', 'Standard'), ('reference', 'Reference'), ('non_historized', 'Non-Historized'), ('multi_active', 'Multi-Active')], default='standard', help_text='Type of satellite', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the satellite was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the satellite was last updated')),
                ('parent_hub', models.ForeignKey(blank=True, help_text='Parent hub (if satellite belongs to a hub)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satellites', to='engine.hub')),
                ('project', models.ForeignKey(help_text='Project this satellite belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='satellites', to='engine.project')),
            ],
            options={
                'db_table': 'satellite',
                'ordering': ['satellite_physical_name'],
                'unique_together': {('project', 'satellite_physical_name')},
            },
        ),
        migrations.CreateModel(
            name='SatelliteColumn',
            fields=[
                ('satellite_column_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the satellite column', primary_key=True, serialize=False)),
                ('is_multi_active_key', models.BooleanField(default=False, help_text='If true, this column is part of the multi-active key (for multi-active satellites)')),
                ('include_in_delta_detection', models.BooleanField(default=True, help_text='If false, this column is excluded from hashdiff calculation')),
                ('target_column_name', models.CharField(blank=True, help_text='Optional target column name (if different from source column name)', max_length=255, null=True)),
                ('target_column_transformation', models.TextField(blank=True, help_text='Optional transformation expression for derived columns (future use)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the satellite column was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the satellite column was last updated')),
                ('satellite', models.ForeignKey(help_text='Satellite this column belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='engine.satellite')),
                ('source_column', models.ForeignKey(help_text='Source column providing the data', on_delete=django.db.models.deletion.PROTECT, related_name='satellite_columns', to='engine.sourcecolumn')),
            ],
            options={
                'db_table': 'satellite_column',
                'ordering': ['satellite', 'source_column'],
                'unique_together': {('satellite', 'source_column')},
            },
        ),
    ]
