# Generated by Django 6.0.5 on 2026-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_generationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='create_record_tracking_satellite',
            field=models.BooleanField(default=False, help_text='If true, a record-tracking satellite should be generated for this link'),
        ),
    ]
