# Generated by Django 6.0 on 2025-12-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_add_link_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkcolumn',
            options={'ordering': ['link', 'sort_order', 'column_name']},
        ),
        migrations.AddField(
            model_name='linkcolumn',
            name='parent_hub',
            field=models.ForeignKey(blank=True, help_text='Parent hub (required for business_key columns)', limit_choices_to={'hub_type': 'standard'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='link_columns', to='engine.hub'),
        ),
        migrations.AddField(
            model_name='linkcolumn',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Order of column for hashkey composition'),
        ),
        migrations.AddField(
            model_name='linksourcemapping',
            name='is_primary_source',
            field=models.BooleanField(default=True, help_text='If true, this is the primary source for multi-source links'),
        ),
        migrations.AlterField(
            model_name='linkcolumn',
            name='column_type',
            field=models.CharField(choices=[('business_key', 'Business Key'), ('payload', 'Payload'), ('additional_column', 'Additional Column')], help_text='Type of column: business_key, payload, or additional_column', max_length=20),
        ),
        migrations.DeleteModel(
            name='LinkHubSourceMapping',
        ),
    ]
