# Generated by Django 6.0.5 on 2026-07-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_link_create_record_tracking_satellite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='create_effectivity_satellite',
            field=models.BooleanField(default=False, help_text='If true, an effectivity satellite should be generated for this hub'),
        ),
    ]
