# Generated by Django 6.0.8 on 2026-09-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_alter_hub_create_effectivity_satellite'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubcolumn',
            name='target_column_transformation',
            field=models.TextField(blank=True, help_text='Optional transformation expression for derived columns (applied in the stage before hashing)', null=True),
        ),
        migrations.AddField(
            model_name='linkcolumn',
            name='target_column_transformation',
            field=models.TextField(blank=True, help_text='Optional transformation expression for derived columns (applied in the stage before hashing)', null=True),
        ),
    ]
