# Generated by Django 6.0 on 2025-12-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_refactor_link_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkcolumn',
            name='parent_hub',
        ),
    ]
