# Generated by Django 6.0 on 2025-12-23 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_remove_link_parent_hub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the group', primary_key=True, serialize=False)),
                ('group_name', models.CharField(help_text="Name of the group (e.g., 'sales', 'marketing', 'core')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of this group', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the group was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the group was last updated')),
                ('project', models.ForeignKey(help_text='Project this group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='engine.project')),
            ],
            options={
                'db_table': 'group',
                'ordering': ['group_name'],
                'unique_together': {('project', 'group_name')},
            },
        ),
        migrations.AddField(
            model_name='hub',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional group for organizing hubs into subfolders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubs', to='engine.group'),
        ),
        migrations.AddField(
            model_name='link',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional group for organizing links into subfolders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='engine.group'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional group for organizing satellites into subfolders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satellites', to='engine.group'),
        ),
    ]
