# Generated by Django 6.0.5 on 2026-09-27 10:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0014_hubcolumn_target_column_transformation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hub",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the hub, written to the generated dbt docs",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hubcolumn",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the column. Falls back to the source column's description",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hubcolumn",
            name="target_column_datatype",
            field=models.CharField(
                blank=True,
                help_text="Data type of the transformed value. Defaults to the source column's data type",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the link, written to the generated dbt docs",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="linkcolumn",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the column. Falls back to the source column's description",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="linkcolumn",
            name="target_column_datatype",
            field=models.CharField(
                blank=True,
                help_text="Data type of the transformed value. Defaults to the source column's data type",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="referencetable",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the reference table, written to the generated dbt docs",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="satellite",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the satellite, written to the generated dbt docs",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="satellitecolumn",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the column. Falls back to the source column's description",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="satellitecolumn",
            name="target_column_datatype",
            field=models.CharField(
                blank=True,
                help_text="Data type of the transformed value. Defaults to the source column's data type",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sourcecolumn",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the column. Raw Vault columns loaded from it inherit it unless they set their own",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sourcesystem",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the source system",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sourcetable",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the source table, written to the generated dbt docs",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="satellitecolumn",
            name="target_column_transformation",
            field=models.TextField(
                blank=True,
                help_text="Optional transformation expression, applied in the stage as a derived column",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stagingcolumn",
            name="prejoin_column",
            field=models.ForeignKey(
                blank=True,
                help_text="Prejoin extraction column (exactly one of the three column kinds)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staging_representations",
                to="engine.prejoinextractioncolumn",
            ),
        ),
        migrations.AlterField(
            model_name="stagingcolumn",
            name="source_column",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct source column (exactly one of the three column kinds)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staging_representations",
                to="engine.sourcecolumn",
            ),
        ),
        migrations.CreateModel(
            name="DerivedColumn",
            fields=[
                (
                    "derived_column_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of the derived column",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "column_name",
                    models.CharField(
                        help_text="Name of the column in the stage (e.g. customer_full_name)",
                        max_length=255,
                    ),
                ),
                (
                    "expression",
                    models.TextField(
                        help_text="SQL expression that computes the value from the source table's columns, in the target platform's dialect"
                    ),
                ),
                (
                    "datatype",
                    models.CharField(
                        blank=True,
                        help_text="Data type of the computed value. datavault4dbt needs it to build ghost records for an expression",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description, inherited by Raw Vault columns loaded from it",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the derived column was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the derived column was last updated",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this derived column belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_columns",
                        to="engine.project",
                    ),
                ),
                (
                    "source_table",
                    models.ForeignKey(
                        help_text="Source table whose stage computes this column",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_columns",
                        to="engine.sourcetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Derived Column",
                "verbose_name_plural": "Derived Columns",
                "db_table": "derived_column",
                "ordering": ["source_table", "column_name"],
                "unique_together": {("source_table", "column_name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="stagingcolumn",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="stagingcolumn",
            name="derived_column",
            field=models.ForeignKey(
                blank=True,
                help_text="Derived column (exactly one of the three column kinds)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staging_representations",
                to="engine.derivedcolumn",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stagingcolumn",
            unique_together={
                ("source_table", "source_column", "prejoin_column", "derived_column")
            },
        ),
    ]
