# Generated by Django 6.0 on 2025-12-23 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_add_group_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceTable',
            fields=[
                ('reference_table_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the reference table', primary_key=True, serialize=False)),
                ('reference_table_physical_name', models.CharField(help_text='Physical name of the reference table', max_length=255)),
                ('historization_type', models.CharField(choices=[('latest', 'Latest'), ('full', 'Full History'), ('snapshot_based', 'Snapshot-Based')], default='latest', help_text='Historization strategy: latest, full, or snapshot_based', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the reference table was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the reference table was last updated')),
                ('project', models.ForeignKey(help_text='Project this reference table belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reference_tables', to='engine.project')),
                ('reference_hub', models.ForeignKey(help_text='Reference hub this table is based on (must be a reference hub)', limit_choices_to={'hub_type': 'reference'}, on_delete=django.db.models.deletion.CASCADE, related_name='reference_tables', to='engine.hub')),
                ('snapshot_control_logic', models.ForeignKey(blank=True, help_text='Snapshot control logic (required if historization_type is snapshot_based)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_tables', to='engine.snapshotcontrollogic')),
                ('snapshot_control_table', models.ForeignKey(blank=True, help_text='Snapshot control table (required if historization_type is snapshot_based)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_tables', to='engine.snapshotcontroltable')),
            ],
            options={
                'db_table': 'reference_table',
                'ordering': ['project', 'reference_table_physical_name'],
                'unique_together': {('project', 'reference_table_physical_name')},
            },
        ),
        migrations.CreateModel(
            name='ReferenceTableSatelliteAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the satellite assignment', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the assignment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the assignment was last updated')),
                ('exclude_columns', models.ManyToManyField(blank=True, help_text='Specific columns to exclude (only used if include_columns is empty)', related_name='excluded_from_reference_tables', to='engine.satellitecolumn')),
                ('include_columns', models.ManyToManyField(blank=True, help_text='Specific columns to include (if empty, includes all except excluded)', related_name='included_in_reference_tables', to='engine.satellitecolumn')),
                ('reference_satellite', models.ForeignKey(help_text='Reference satellite to include (must be a reference satellite)', limit_choices_to={'satellite_type': 'reference'}, on_delete=django.db.models.deletion.CASCADE, related_name='reference_table_assignments', to='engine.satellite')),
                ('reference_table', models.ForeignKey(help_text='Reference table this assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='satellite_assignments', to='engine.referencetable')),
            ],
            options={
                'db_table': 'reference_table_satellite_assignment',
                'ordering': ['reference_table', 'reference_satellite'],
                'unique_together': {('reference_table', 'reference_satellite')},
            },
        ),
    ]
