# Generated by Django 6.0.5 on 2026-10-03 18:26

from django.db import migrations, models

_TABLE_VALUES = (
    "record_source_value",
    "static_part_of_record_source",
    "load_date_value",
)


def blank_means_inherit(apps, schema_editor) -> None:
    """A table value stored as "" (old Excel and JSON imports) now inherits."""
    SourceTable = apps.get_model("engine", "SourceTable")
    for field in _TABLE_VALUES:
        SourceTable.objects.filter(**{field: ""}).update(**{field: None})


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0016_record_source_fallback_as_fixed_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcesystem",
            name="load_date_value",
            field=models.CharField(
                blank=True,
                help_text="Load date of this system's tables that set none",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sourcesystem",
            name="record_source_value",
            field=models.CharField(
                blank=True,
                help_text="Record source of this system's tables that set none",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sourcesystem",
            name="static_part_of_record_source",
            field=models.CharField(
                blank=True,
                help_text="Static part of the record source of this system's tables that set none",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourcetable",
            name="load_date_value",
            field=models.CharField(
                blank=True,
                help_text="Load date: a column or SQL. Empty inherits",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourcetable",
            name="record_source_value",
            field=models.CharField(
                blank=True,
                help_text="Record source: a column, SQL, or fixed text after a '!'. Empty inherits",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourcetable",
            name="static_part_of_record_source",
            field=models.CharField(
                blank=True,
                help_text="Part of the record source that stays the same across loads. Empty inherits",
                max_length=500,
                null=True,
            ),
        ),
        migrations.RunPython(blank_means_inherit, migrations.RunPython.noop),
    ]
