# Generated by Django 6.0 on 2025-12-23 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0016_referencetable_referencetablesatelliteassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PIT",
            fields=[
                (
                    "pit_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of the PIT structure",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pit_physical_name",
                    models.CharField(
                        help_text="Physical name of the PIT structure", max_length=255
                    ),
                ),
                (
                    "tracked_entity_type",
                    models.CharField(
                        choices=[("hub", "Hub"), ("link", "Link")],
                        help_text="Type of entity being tracked (hub or link)",
                        max_length=10,
                    ),
                ),
                (
                    "dimension_key_column_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional dimension key column name in the PIT",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pit_type",
                    models.CharField(
                        blank=True,
                        help_text="Optional PIT type classification",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "custom_record_source",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom record source value",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "use_snapshot_optimization",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to apply snapshot optimization techniques",
                    ),
                ),
                (
                    "include_business_objects_before_appearance",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to include business keys before their first appearance",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the PIT was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the PIT was last updated",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this PIT belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pits",
                        to="engine.project",
                    ),
                ),
                (
                    "satellites",
                    models.ManyToManyField(
                        help_text="Satellites included in this PIT structure",
                        related_name="pits",
                        to="engine.satellite",
                    ),
                ),
                (
                    "snapshot_control_logic",
                    models.ForeignKey(
                        help_text="Snapshot control logic for this PIT",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pits",
                        to="engine.snapshotcontrollogic",
                    ),
                ),
                (
                    "snapshot_control_table",
                    models.ForeignKey(
                        help_text="Snapshot control table for this PIT",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pits",
                        to="engine.snapshotcontroltable",
                    ),
                ),
                (
                    "tracked_hub",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hub being tracked (if tracked_entity_type is 'hub')",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pits",
                        to="engine.hub",
                    ),
                ),
                (
                    "tracked_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link being tracked (if tracked_entity_type is 'link')",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pits",
                        to="engine.link",
                    ),
                ),
            ],
            options={
                "verbose_name": "PIT",
                "verbose_name_plural": "PITs",
                "db_table": "pit",
                "ordering": ["project", "pit_physical_name"],
                "unique_together": {("project", "pit_physical_name")},
            },
        ),
    ]
