# Generated by Django 6.0 on 2025-12-23 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0017_pit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hubsourcemapping",
            name="source_column",
            field=models.ForeignKey(
                help_text="Source column providing the data",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_mappings",
                to="engine.sourcecolumn",
            ),
        ),
        migrations.AlterField(
            model_name="linksourcemapping",
            name="source_column",
            field=models.ForeignKey(
                help_text="Source column providing the data",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_column_mappings",
                to="engine.sourcecolumn",
            ),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="source_table",
            field=models.ForeignKey(
                blank=True,
                help_text="Source table that feeds this satellite (all columns must come from this table)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="satellites",
                to="engine.sourcetable",
            ),
        ),
        migrations.AlterField(
            model_name="satellitecolumn",
            name="source_column",
            field=models.ForeignKey(
                help_text="Source column providing the data",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="satellite_columns",
                to="engine.sourcecolumn",
            ),
        ),
    ]
