# Generated by Django 6.0 on 2025-12-23 10:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0018_fix_cascade_deletion"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrejoinDefinition",
            fields=[
                (
                    "prejoin_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of the prejoin definition",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prejoin_operator",
                    models.CharField(
                        choices=[("AND", "AND"), ("OR", "OR")],
                        default="AND",
                        help_text="Operator for combining multiple join conditions (AND/OR)",
                        max_length=3,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the prejoin was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the prejoin was last updated",
                    ),
                ),
                (
                    "prejoin_condition_source_column",
                    models.ManyToManyField(
                        help_text="Join column(s) from the source table",
                        related_name="prejoin_conditions_as_source",
                        to="engine.sourcecolumn",
                    ),
                ),
                (
                    "prejoin_condition_target_column",
                    models.ManyToManyField(
                        help_text="Join column(s) from the target table",
                        related_name="prejoin_conditions_as_target",
                        to="engine.sourcecolumn",
                    ),
                ),
                (
                    "prejoin_target_table",
                    models.ForeignKey(
                        help_text="Target table to join (right side of join)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prejoins_as_target",
                        to="engine.sourcetable",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this prejoin belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prejoins",
                        to="engine.project",
                    ),
                ),
                (
                    "source_table",
                    models.ForeignKey(
                        help_text="Main source table (left side of join)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prejoins_as_source",
                        to="engine.sourcetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prejoin Definition",
                "verbose_name_plural": "Prejoin Definitions",
                "db_table": "prejoin_definition",
                "ordering": ["source_table", "prejoin_target_table"],
            },
        ),
        migrations.CreateModel(
            name="PrejoinExtractionColumn",
            fields=[
                (
                    "extraction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of the extraction column",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the extraction column was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the extraction column was last updated",
                    ),
                ),
                (
                    "prejoin",
                    models.ForeignKey(
                        help_text="Prejoin definition this extraction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_columns",
                        to="engine.prejoindefinition",
                    ),
                ),
                (
                    "source_column",
                    models.ForeignKey(
                        help_text="Column from the target table to extract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prejoin_extractions",
                        to="engine.sourcecolumn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prejoin Extraction Column",
                "verbose_name_plural": "Prejoin Extraction Columns",
                "db_table": "prejoin_extraction_column",
                "ordering": ["prejoin", "source_column"],
                "unique_together": {("prejoin", "source_column")},
            },
        ),
    ]
