# Generated by Django 5.1.4 on 2025-12-28 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0021_add_name_to_snapshot_control"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "category_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of the template category",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'DataVault4dbt', 'Custom')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this template category"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Template categories",
                "db_table": "template_category",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="snapshotcontroltable",
            name="name",
            field=models.CharField(
                default="control_snap",
                help_text="Base name of the snapshot control (e.g., 'control_snap')",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="ModelTemplate",
            fields=[
                (
                    "template_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of the template",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for identification", max_length=100
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("stage", "Stage"),
                            ("hub_standard", "Hub (Standard)"),
                            ("hub_reference", "Hub (Reference)"),
                            ("link_standard", "Link (Standard)"),
                            ("link_non_historized", "Link (Non-Historized)"),
                            ("satellite_standard", "Satellite (Standard)"),
                            ("satellite_non_historized", "Satellite (Non-Historized)"),
                            ("satellite_reference", "Satellite (Reference)"),
                            ("satellite_multi_active", "Satellite (Multi-Active)"),
                            ("satellite_effectivity", "Effectivity Satellite"),
                            ("satellite_record_tracking", "Record Tracking Satellite"),
                            ("satellite_v1", "Satellite V1 (Load-End-Date View)"),
                            ("pit", "PIT"),
                            ("reference_table", "Reference Table"),
                            ("snapshot_control_v0", "Snapshot Control Table (V0)"),
                            ("snapshot_control_v1", "Snapshot Control Logic (V1)"),
                        ],
                        help_text="Entity type this template applies to",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this template variant"
                    ),
                ),
                (
                    "sql_template_content",
                    models.TextField(
                        blank=True,
                        help_text="Jinja2 template for SQL model file. Leave blank to use file-based default.",
                    ),
                ),
                (
                    "yaml_template_content",
                    models.TextField(
                        blank=True,
                        help_text="Jinja2 template for YAML schema file. Leave blank to use file-based default.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Priority for template selection. Higher values are preferred.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is active and available for selection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category for organizing templates",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="engine.templatecategory",
                    ),
                ),
            ],
            options={
                "db_table": "model_template",
                "ordering": ["entity_type", "-priority", "name"],
                "unique_together": {("entity_type", "name")},
            },
        ),
    ]
