# Generated by Django 6.0 on 2026-01-15 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0022_templatecategory_alter_snapshotcontroltable_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linkcolumn",
            options={"ordering": ["link", "column_name"]},
        ),
        migrations.AlterUniqueTogether(
            name="linksourcemapping",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="link",
            name="group",
        ),
        migrations.RemoveField(
            model_name="link",
            name="hub_references",
        ),
        migrations.RemoveField(
            model_name="link",
            name="link_hashkey_name",
        ),
        migrations.RemoveField(
            model_name="linkcolumn",
            name="sort_order",
        ),
        migrations.AlterField(
            model_name="linkcolumn",
            name="column_type",
            field=models.CharField(
                choices=[
                    ("payload", "Payload"),
                    ("additional_column", "Additional Column"),
                ],
                help_text="Type of column: payload or additional_column",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="linksourcemapping",
            name="link_source_mapping_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for a link column mapping",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="linksourcemapping",
            name="source_column",
            field=models.ForeignKey(
                blank=True,
                help_text="Source column mapped to this link column",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_column_mappings",
                to="engine.sourcecolumn",
            ),
        ),
        migrations.CreateModel(
            name="LinkHubReference",
            fields=[
                (
                    "link_hub_reference_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the link-to-hub reference",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hub_hashkey_alias_in_link",
                    models.CharField(
                        blank=True,
                        help_text="Alias for the hub hashkey in the link. Default should be the hub's hashkey name.",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "hub",
                    models.ForeignKey(
                        help_text="Hub referenced by the link",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_references",
                        to="engine.hub",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        help_text="Link this reference belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_references",
                        to="engine.link",
                    ),
                ),
            ],
            options={
                "db_table": "link_hub_references",
                "ordering": ["link", "hub"],
            },
        ),
        migrations.CreateModel(
            name="LinkHubSourceMapping",
            fields=[
                (
                    "link_hub_source_mapping_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for a link hub mapping",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the mapping was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the mapping was last updated",
                    ),
                ),
                (
                    "link_hub_reference",
                    models.ForeignKey(
                        help_text="Link hub reference being mapped",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_mappings",
                        to="engine.linkhubreference",
                    ),
                ),
                (
                    "prejoin_extraction_column",
                    models.ForeignKey(
                        blank=True,
                        help_text="Prejoin extraction column (XOR with source_column)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_hub_mappings",
                        to="engine.prejoinextractioncolumn",
                    ),
                ),
                (
                    "source_column",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct source column (XOR with prejoin_extraction_column)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_hub_mappings",
                        to="engine.sourcecolumn",
                    ),
                ),
                (
                    "standard_hub_column",
                    models.ForeignKey(
                        help_text="Hub column of the referenced standard hub",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_hub_mappings",
                        to="engine.hubcolumn",
                    ),
                ),
            ],
            options={
                "db_table": "link_hub_source_mapping",
                "ordering": ["link_hub_reference", "standard_hub_column"],
            },
        ),
        migrations.RemoveField(
            model_name="linksourcemapping",
            name="is_primary_source",
        ),
        migrations.RemoveField(
            model_name="linksourcemapping",
            name="prejoin_extraction_column",
        ),
    ]
