# Generated by Django 6.0 on 2026-01-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0028_make_record_source_and_load_date_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="prejoinextractioncolumn",
            name="prejoin_target_column_alias",
            field=models.CharField(
                blank=True,
                help_text="Optional alias for the extracted column in the dbt stage. Will overwrite physical column name.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="link_hashkey_name",
            field=models.CharField(
                default="",
                help_text="Name of the link hashkey column (e.g. hk_customer_order_l)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="link_physical_name",
            field=models.CharField(
                help_text="Physical name of the link (e.g. customer_order_l)",
                max_length=255,
            ),
        ),
    ]
